### ISSUE TITLE
TODO Idea Tracker for Coral Docs

### ISSUE THREAD

**Issue by sfphoenix** [coralproject/docs#72]
In no particular order:
- [ ] Review all open issues
- [ ] Figure out relative image links for MkDocs --> github
- [ ] Convert each product to single MD page in MkDocs
- [ ] Create documentation templates for products, components, services, API endpoints
- [ ] Incorporate numbers steps into all docs
- [ ] Add documentation date for freshness check
- [ ] Ensure API's have sample data sets listed in docs
- [ ] Evaluate and discuss MkDocs theme
- [ ] Evaluate and discuss hosting home for docs
- [ ] Review and discuss docs automation script to push updates to AWS
- [ ] Standardize image folder in MkDocs
- [ ] Add help tab in docs for users to give feedback or request install assistance (@gabelula)
- [x] Add Google Analytics to documentation site to track usage
